export interface Product {
  id: string
  name: string
  price: number
  image: string
  description: string
  category: string
  inStock: boolean
}

export const products: Product[] = [
  {
    id: "p2",
    name: "Midnight Essence",
    price: 89.99,
    image: "/elegant-black-perfume-bottle-with-gold-accents.jpg",
    description: "A mysterious and alluring fragrance with notes of black orchid and vanilla",
    category: "Evening",
    inStock: true,
  },
  {
    id: "p3",
    name: "Ocean Breeze",
    price: 75.5,
    image: "/blue-perfume-bottle-with-wave-design.jpg",
    description: "Fresh aquatic scent with hints of sea salt and citrus",
    category: "Fresh",
    inStock: true,
  },
  {
    id: "p4",
    name: "Rose Garden",
    price: 95.0,
    image: "/pink-rose-perfume-bottle-with-floral-design.jpg",
    description: "Romantic floral bouquet with Bulgarian rose and peony",
    category: "Floral",
    inStock: true,
  },
  {
    id: "p5",
    name: "Amber Nights",
    price: 110.0,
    image: "/amber-colored-perfume-bottle-with-warm-glow.jpg",
    description: "Warm and sensual with amber, sandalwood, and musk",
    category: "Oriental",
    inStock: true,
  },
  {
    id: "p6",
    name: "Citrus Burst",
    price: 65.99,
    image: "/yellow-citrus-perfume-bottle-with-fresh-design.jpg",
    description: "Energizing blend of lemon, bergamot, and grapefruit",
    category: "Citrus",
    inStock: true,
  },
  {
    id: "p7",
    name: "Velvet Dreams",
    price: 125.0,
    image: "/purple-velvet-perfume-bottle-luxury-design.jpg",
    description: "Luxurious blend of iris, cashmere wood, and white musk",
    category: "Luxury",
    inStock: true,
  },
  {
    id: "p8",
    name: "Wild Forest",
    price: 85.75,
    image: "/green-forest-perfume-bottle-with-wood-texture.jpg",
    description: "Earthy and fresh with pine, cedar, and moss",
    category: "Woody",
    inStock: true,
  },
  {
    id: "p9",
    name: "Golden Hour",
    price: 99.99,
    image: "/golden-perfume-bottle-with-sunset-colors.jpg",
    description: "Warm and radiant with honey, vanilla, and golden amber",
    category: "Sweet",
    inStock: true,
  },
  {
    id: "p10",
    name: "Crystal Clear",
    price: 79.5,
    image: "/clear-crystal-perfume-bottle-minimalist-design.jpg",
    description: "Clean and pure with white tea, jasmine, and soft musk",
    category: "Clean",
    inStock: true,
  },
  {
    id: "p11",
    name: "Spice Market",
    price: 105.0,
    image: "/spice-colored-perfume-bottle-with-exotic-design.jpg",
    description: "Exotic blend of cardamom, cinnamon, and black pepper",
    category: "Spicy",
    inStock: true,
  },
  {
    id: "p12",
    name: "Moonlight Serenade",
    price: 115.99,
    image: "/silver-moonlight-perfume-bottle-elegant-design.jpg",
    description: "Ethereal and romantic with white flowers and silver musk",
    category: "Evening",
    inStock: true,
  },
  {
    id: "p13",
    name: "Summer Rain",
    price: 72.0,
    image: "/rain-drop-perfume-bottle-with-water-effect.jpg",
    description: "Fresh and clean like petrichor with green leaves",
    category: "Fresh",
    inStock: true,
  },
  {
    id: "p14",
    name: "Leather & Smoke",
    price: 135.0,
    image: "/dark-leather-perfume-bottle-masculine-design.jpg",
    description: "Bold and masculine with leather, tobacco, and smoky woods",
    category: "Masculine",
    inStock: true,
  },
  {
    id: "p15",
    name: "Cherry Blossom",
    price: 88.5,
    image: "/pink-cherry-blossom-perfume-bottle-spring-design.jpg",
    description: "Delicate and feminine with cherry blossom and soft woods",
    category: "Floral",
    inStock: true,
  },
  {
    id: "p16",
    name: "Desert Wind",
    price: 92.75,
    image: "/desert-sand-perfume-bottle-with-dune-design.jpg",
    description: "Warm and dry with saffron, oud, and desert rose",
    category: "Oriental",
    inStock: true,
  },
  {
    id: "p17",
    name: "Electric Blue",
    price: 98.0,
    image: "/electric-blue-perfume-bottle-modern-design.jpg",
    description: "Modern and vibrant with blue lotus and electric citrus",
    category: "Modern",
    inStock: true,
  },
  {
    id: "p18",
    name: "Vanilla Sky",
    price: 82.99,
    image: "/vanilla-sky-perfume-bottle-cloud-design.jpg",
    description: "Sweet and comforting with Madagascar vanilla and soft clouds",
    category: "Sweet",
    inStock: true,
  },
  {
    id: "p19",
    name: "Mystic Woods",
    price: 108.5,
    image: "/mystical-woods-perfume-bottle-with-forest-magic.jpg",
    description: "Mysterious and deep with ancient woods and forest herbs",
    category: "Woody",
    inStock: true,
  },
  {
    id: "p20",
    name: "Pure Elegance",
    price: 145.0,
    image: "/elegant-white-perfume-bottle-luxury-minimalist.jpg",
    description: "The epitome of sophistication with rare white flowers",
    category: "Luxury",
    inStock: true,
  },
]
